# Microservices related config
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/PlayerDB
    username: postgres
    password: root
    hikari:
      maximum-pool-size: 4
  application:
    name: MS07-PlayerService-v1
  main:
    allow-bean-definition-overriding: true

server:
  port: 8087