# Microservices related config
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/TeamDB
    username: postgres
    password: root
    hikari:
      maximum-pool-size: 4
  application:
    name: MS06-TeamService-v1

server:
  port: 8086